DigitalLifeApp/Models/Invoice.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DigitalLifeApp.Models
{
    public class Invoice
    {
        public int Id { get; set; }
        public int InvoiceNumber  { get; set; }
        [Required]
        public DateTime InvoiceDate { get; set; }
        [Required]
        public int ClientId { get; set; }
        public Client Client { get; set; }
        [Required]
        public double NetAmount { get; set; }
        [Required]
        public double TaxAmount { get; set; }
        [Required]
        public double TotalAmount { get; set; } 
        [Required]
        public int ProjectId { get; set; }
        public Project Project { get; set; }
        public string Note { get; set; }
        public bool PaymentStatus { get; set; }

        public double TotalPrice()
        {
            return ((NetAmount * TaxAmount) / 100);
        }

    }

    
}

DigitalLifeApp/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DigitalLifeApp.DAL;
using DigitalLifeApp.Models;
using DigitalLifeApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DigitalLifeApp.Controllers
{
    public class InvoiceController : Controller
    {
        private readonly AppDbContext context;
        public InvoiceController(AppDbContext _context)
        {
            context = _context;
        }

        //public IEnumerable<Invoice> results { get; set; }

        public IActionResult List()
        {
            return View(context.Invoices.Include(i => i.Client).Include(i => i.Project).ToList());
        }

        [HttpGet]
        public async Task<IActionResult> List(string ProjectSearch)
        {
            ViewData["GetInvoiceDetails"] = ProjectSearch;

            var projectQuery = from x in context.Invoices.Include(i => i.Client).Include(i => i.Project) select x;

            if (!String.IsNullOrEmpty(ProjectSearch))
            {
                projectQuery = projectQuery.Where(x => x.Project.Name.StartsWith(ProjectSearch) ||
                x.Client.Name.StartsWith(ProjectSearch));
            }
            //results = context.Invoices.Include(i => i.Client).Include(i => i.Project).ToList();
            //ViewBag.Results = results;
            return View(await projectQuery.AsNoTracking().ToListAsync());
        }

        //[HttpPost]
        //public IActionResult List(DateTime startTime, DateTime endTime)
        //{            
        //    results = (from x in context.Invoices.Include(i => i.Client).Include(i => i.Project)
        //               where (x.InvoiceDate >= startTime) &&
        //                     (x.InvoiceDate <= endTime)
        //               select x).ToList();

        //    ViewBag.Results = results;

        //    return View();
        //}

        public async Task<IActionResult> Info(int? id)
        {
            if (id == null) return NotFound();

            Invoice invoice = await context.Invoices.Include(i => i.Client).Include(i => i.Project).Where(i => i.Id == id).SingleOrDefaultAsync();
            return View(invoice);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Clients = new SelectList(context.Clients.ToList(), "Id", "Name");
            ViewBag.Projects = new SelectList(context.Projects.ToList(), "Id", "Name");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                context.Invoices.Add(invoice);
                await context.SaveChangesAsync();
                return RedirectToAction("List");
            }

            ViewBag.Clients = new SelectList(context.Clients.ToList(), "Id", "Name");
            ViewBag.Projects = new SelectList(context.Projects.ToList(), "Id", "Name");

            return View(invoice);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            ViewBag.Clients = new SelectList(context.Clients.ToList(), "Id", "Name");
            ViewBag.Projects = new SelectList(context.Projects.ToList(), "Id", "Name");

            Invoice invoice = await context.Invoices.Include(i => i.Client).Include(i => i.Project).FirstOrDefaultAsync(i => i.Id == id);

            return View(invoice);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                context.Invoices.Update(invoice);
                await context.SaveChangesAsync();
                return RedirectToAction("List");
            }

            ViewBag.Clients = new SelectList(context.Clients.ToList(), "Id", "Name");
            ViewBag.Projects = new SelectList(context.Projects.ToList(), "Id", "Name");

            return View(invoice);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            Invoice invoice = context.Invoices.Find(id);
            context.Invoices.Remove(invoice);
            await context.SaveChangesAsync();
            return RedirectToAction("List");
        }

    }
}

DigitalLifeApp/Views/Invoice/Create.cshtml
@model Invoice
@{ 
    ViewData["Title"] = "Create"; 
}

<div style="background: #1979a9; padding: 15px; color: #fff;">
    <h2 class="m-0">Create Invoice</h2>
</div>

<form method="post" asp-controller="Invoice" asp-action="Create" class="m-2">
    <div class="text-danger" asp-validation-summary="All"></div>

    <div class="form-group">
        <label>Invoice Number:</label>
        <input asp-for="InvoiceNumber" class="form-control" />
    </div>
    <div class="form-group">
        <label>Invoice Date:</label>
        <br />
        <input type="date" asp-for="InvoiceDate" />
    </div>
    <div class="form-group">
        <label>Clients:</label>
        <select class="form-control" asp-for="ClientId" asp-items="ViewBag.Clients">
            <option disabled selected value="">
                ---- Select Client ----
            </option>
        </select>
    </div>
    <div class="form-group">
        <label>Projects:</label>
        <select class="form-control" asp-for="ProjectId" asp-items="ViewBag.Projects">
            <option disabled selected value="">
                ---- Select Project ----
            </option>
        </select>
    </div>
    <div class="form-group">
        <label>Note:</label>
        <textarea asp-for="Note" rows="10" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label>Net Amount:</label>
        <input asp-for="NetAmount" class="form-control" />
    </div>
    <div class="form-group">
        <label>Tax Amount (%):</label>
        <input asp-for="TaxAmount" class="form-control" />
    </div>
  
    <div class="form-check">
        <label class="form-check-label">
            <input asp-for="PaymentStatus" class="form-check-input" />
            Payment Status
        </label>
    </div>
    <br />
    <br />

    <button type="submit" class="btn btn-primary btn-icon-text">
        <i class="mdi mdi-file-check btn-icon-prepend"></i>
        Submit
    </button>
    <button asp-action="List" type="submit" class="btn btn-secondary btn-icon-text">
        <i class="mdi mdi-reload btn-icon-prepend"></i>
        Cancel
    </button>
</form>

DigitalLifeApp/Views/Invoice/Info.cshtml
@model Invoice
@{ ViewData["Title"] = "Info"; }

<div style="background: #1979a9; padding: 15px; color: #fff;">
    <h2 class="m-0">@Model.InvoiceNumber Invoice Info</h2>
</div>

<form action="#" class="m-2">
    <div class="form-group">
        <label>Project Name:</label>
        <input asp-for="Project.Name" class="form-control" disabled />
    </div>
    <div class="form-group">
        <label>Note:</label>
        <textarea asp-for="Note" class="form-control" cols="" rows="10" disabled></textarea>
    </div>
</form>

<a asp-action="List" class="btn btn-secondary btn-icon-text">
    <i class="mdi mdi-reload btn-icon-prepend"></i>
    Cancel
</a>

DigitalLifeApp/Views/Invoice/List.cshtml
@model IEnumerable<Invoice>

@{ ViewData["Title"] = "List"; }

<div style="background: #1979a9; padding: 15px; color: #fff;">
    <h2 class="m-0">Invoice List</h2>
</div>

@if (Model.Count() == 0)
{
<p style="text-align: center;
    font-size: 25px;
    font-family: auto;
    margin: 40px 0px;">No Invoices</p> }
            else
            {
                <form method="get" asp-action="List">
                    <p>
                        <input style="width: 730px; border: none; padding: 15px; margin-top: 10px;" type="search" name="ProjectSearch" value="@ViewData["GetInvoiceDetails"]" placeholder="Enter Project Name Or Client Name..." />
                        <input type="submit" value="Search" class="btn btn-primary" />
                        <a asp-action="List">Get All Invoices</a>
                    </p>
                </form>

                @*<form method="post">
                    <div class="form-group mb-3">
                        <span> Start Date:</span>
                        <input type="date" name="startTime" />
                        <span> End Date:</span>
                        <input type="date" name="endTime" />
                        <input type="submit" value="Search" class="btn btn-primary" />
                    </div>*@


    <div class="text-danger" asp-validation-summary="ModelOnly"></div>
    <table class="table">
        <thead class="thead-light">
            <tr>
                <th scope="col">Invoice Number</th>
                <th scope="col">Invoice Date</th>
                <th scope="col">Client</th>
                <th scope="col">Project Name</th>
                <th scope="col">Net Amount</th>
                <th scope="col">Tax Amount</th>
                <th scope="col">Total Amount</th>
                <th scope="col">Payment Status</th>
            </tr>
        </thead>
        <tbody>
            @*ViewData["Results"] as IEnumerable<Invoice>*@
            @foreach (var invoice in Model)
            {
<tr>
    <td>@invoice.InvoiceNumber</td>
    <td>@invoice.InvoiceDate.ToString("dd MMM yyyy")</td>
    <td>@invoice.Client.Name @invoice.Client.Surname</td>
    <td>@invoice.Project.Name</td>
    <td>@invoice.NetAmount</td>
    <td>@invoice.TaxAmount</td>
    <td>@invoice.TotalPrice()</td>
    <td>
        @if (!invoice.PaymentStatus)
        {
<p>Pending</p> }
else
{
<p>Done</p>}
    </td>

    <td>
        <form class="d-flex" asp-route-id="@invoice.Id" asp-action="Delete" method="post">
            <a class="btn btn-info d-flex justify-content-center" style="width:20px" asp-controller="Invoice" asp-action="Info" asp-route-id="@invoice.Id">
                <i class="fas fa-info-circle"></i>
            </a>
            <button type="submit" class="btn btn-danger d-flex justify-content-center" style="width:20px"><i class="fas fa-trash"></i></button>
            <a class="btn btn-primary d-flex justify-content-center" style="width:20px" asp-action="Update" asp-route-id="@invoice.Id"><i class="far fa-edit"></i></a>
        </form>
    </td>
</tr>
}
        </tbody>
        <tfoot>
            <tr>
                <td style="font-weight:bold; font-size:18px" colspan="4">Total:</td>
                <td style="font-weight:bold; font-size:18px">@Model.Sum(na => na.NetAmount)</td>
                <td style="font-weight:bold; font-size:18px">@Model.Sum(ta => ta.TaxAmount)</td>
                <td style="font-weight:bold; font-size:18px">@Model.Sum(totala => totala.TotalPrice())</td>
            </tr>
        </tfoot>
    </table>

            }

DigitalLifeApp/Views/Invoice/Update.cshtml
@model Invoice

@{ ViewData["Title"] = "Update"; }

<div style="background: #1979a9; padding: 15px; color: #fff;">
    <h2 class="m-0">@Model.InvoiceNumber Invoice Update</h2>
</div>

<form method="post" asp-controller="Invoice" asp-action="Update" class="m-2">
    @Html.AntiForgeryToken()

    <div class="text-danger" asp-validation-summary="All"></div>
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label>Invoice Number:</label>
        <input asp-for="InvoiceNumber" class="form-control" />
    </div>
    <div class="form-group">
        <label>Invoice Date:</label>
        <br />
        <input type="date" asp-for="InvoiceDate" />
    </div>
    <div class="form-group">
        <label>Clients:</label>
        <select class="form-control" asp-for="ClientId" asp-items="ViewBag.Clients">
            <option disabled selected value="">
                ---- Select Client ----
            </option>
        </select>
    </div>
    <div class="form-group">
        <label>Projects:</label>
        <select class="form-control" asp-for="ProjectId" asp-items="ViewBag.Projects">
            <option disabled selected value="">
                ---- Select Project ----
            </option>
        </select>
    </div>
    <div class="form-group">
        <label>Note:</label>
        <textarea asp-for="Note" rows="10" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label>Net Amount:</label>
        <input asp-for="NetAmount" class="form-control" />
    </div>
    <div class="form-group">
        <label>Tax Amount (%):</label>
        <input asp-for="TaxAmount" class="form-control" />
    </div>
    <div class="form-group">
        <label>Total Amount:</label>
        <p style="font-size:20px; font-weight:bold">@Model.TotalPrice()</p>
    </div>
    <div class="form-check">
        <label class="form-check-label">
            <input asp-for="PaymentStatus" class="form-check-input" />
            Payment Status
        </label>
    </div>
    <br />
    <br />

    <button type="submit" class="btn btn-primary btn-icon-text">
        <i class="mdi mdi-file-check btn-icon-prepend"></i>
        Submit
    </button>
    <button asp-action="List" type="submit" class="btn btn-secondary btn-icon-text">
        <i class="mdi mdi-reload btn-icon-prepend"></i>
        Cancel
    </button>
</form>